#############################################################################
# Makefile for building: test
# Generated by qmake (3.0) (Qt 5.3.2)
# Project:  test.pro
# Template: app
# Command: /home/lzs/qt/5.3/gcc_64/bin/qmake -o Makefile test.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_QUICK_LIB -DQT_QML_LIB -DQT_WIDGETS_LIB -DQT_NETWORK_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIE $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT -fPIE $(DEFINES)
INCPATH       = -I../../qt/5.3/gcc_64/mkspecs/linux-g++ -I. -I. -I../../qt/5.3/gcc_64/include -I../../qt/5.3/gcc_64/include/QtQuick -I../../qt/5.3/gcc_64/include/QtQml -I../../qt/5.3/gcc_64/include/QtWidgets -I../../qt/5.3/gcc_64/include/QtNetwork -I../../qt/5.3/gcc_64/include/QtGui -I../../qt/5.3/gcc_64/include/QtCore -I.
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/home/lzs/qt/5.3/gcc_64 -Wl,-rpath,/home/lzs/qt/5.3/gcc_64/lib
LIBS          = $(SUBLIBS) -L/home/lzs/qt/5.3/gcc_64/lib -lQt5Quick -lQt5Qml -lQt5Widgets -lQt5Network -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /home/lzs/qt/5.3/gcc_64/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = mainwindow.cpp \
		mainwindow2.cpp \
		test.cpp \
		dia_spd.cpp moc_mainwindow.cpp \
		moc_mainwindow2.cpp \
		moc_dia_spd.cpp
OBJECTS       = mainwindow.o \
		mainwindow2.o \
		test.o \
		dia_spd.o \
		moc_mainwindow.o \
		moc_mainwindow2.o \
		moc_dia_spd.o
DIST          = ../../qt/5.3/gcc_64/mkspecs/features/spec_pre.prf \
		../../qt/5.3/gcc_64/mkspecs/common/shell-unix.conf \
		../../qt/5.3/gcc_64/mkspecs/common/unix.conf \
		../../qt/5.3/gcc_64/mkspecs/common/linux.conf \
		../../qt/5.3/gcc_64/mkspecs/common/gcc-base.conf \
		../../qt/5.3/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../qt/5.3/gcc_64/mkspecs/common/g++-base.conf \
		../../qt/5.3/gcc_64/mkspecs/common/g++-unix.conf \
		../../qt/5.3/gcc_64/mkspecs/qconfig.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_enginio.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../qt/5.3/gcc_64/mkspecs/features/qt_functions.prf \
		../../qt/5.3/gcc_64/mkspecs/features/qt_config.prf \
		../../qt/5.3/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../qt/5.3/gcc_64/mkspecs/features/spec_post.prf \
		../../qt/5.3/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../qt/5.3/gcc_64/mkspecs/features/default_pre.prf \
		../../qt/5.3/gcc_64/mkspecs/features/resolve_config.prf \
		../../qt/5.3/gcc_64/mkspecs/features/default_post.prf \
		../../qt/5.3/gcc_64/mkspecs/features/warn_on.prf \
		../../qt/5.3/gcc_64/mkspecs/features/qt.prf \
		../../qt/5.3/gcc_64/mkspecs/features/resources.prf \
		../../qt/5.3/gcc_64/mkspecs/features/moc.prf \
		../../qt/5.3/gcc_64/mkspecs/features/unix/opengl.prf \
		../../qt/5.3/gcc_64/mkspecs/features/uic.prf \
		../../qt/5.3/gcc_64/mkspecs/features/unix/thread.prf \
		../../qt/5.3/gcc_64/mkspecs/features/testcase_targets.prf \
		../../qt/5.3/gcc_64/mkspecs/features/exceptions.prf \
		../../qt/5.3/gcc_64/mkspecs/features/yacc.prf \
		../../qt/5.3/gcc_64/mkspecs/features/lex.prf \
		test.pro mainwindow.cpp \
		mainwindow2.cpp \
		test.cpp \
		dia_spd.cpp
QMAKE_TARGET  = test
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = test


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: test.pro ../../qt/5.3/gcc_64/mkspecs/linux-g++/qmake.conf ../../qt/5.3/gcc_64/mkspecs/features/spec_pre.prf \
		../../qt/5.3/gcc_64/mkspecs/common/shell-unix.conf \
		../../qt/5.3/gcc_64/mkspecs/common/unix.conf \
		../../qt/5.3/gcc_64/mkspecs/common/linux.conf \
		../../qt/5.3/gcc_64/mkspecs/common/gcc-base.conf \
		../../qt/5.3/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../qt/5.3/gcc_64/mkspecs/common/g++-base.conf \
		../../qt/5.3/gcc_64/mkspecs/common/g++-unix.conf \
		../../qt/5.3/gcc_64/mkspecs/qconfig.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_enginio.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../qt/5.3/gcc_64/mkspecs/features/qt_functions.prf \
		../../qt/5.3/gcc_64/mkspecs/features/qt_config.prf \
		../../qt/5.3/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../qt/5.3/gcc_64/mkspecs/features/spec_post.prf \
		../../qt/5.3/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../qt/5.3/gcc_64/mkspecs/features/default_pre.prf \
		../../qt/5.3/gcc_64/mkspecs/features/resolve_config.prf \
		../../qt/5.3/gcc_64/mkspecs/features/default_post.prf \
		../../qt/5.3/gcc_64/mkspecs/features/warn_on.prf \
		../../qt/5.3/gcc_64/mkspecs/features/qt.prf \
		../../qt/5.3/gcc_64/mkspecs/features/resources.prf \
		../../qt/5.3/gcc_64/mkspecs/features/moc.prf \
		../../qt/5.3/gcc_64/mkspecs/features/unix/opengl.prf \
		../../qt/5.3/gcc_64/mkspecs/features/uic.prf \
		../../qt/5.3/gcc_64/mkspecs/features/unix/thread.prf \
		../../qt/5.3/gcc_64/mkspecs/features/testcase_targets.prf \
		../../qt/5.3/gcc_64/mkspecs/features/exceptions.prf \
		../../qt/5.3/gcc_64/mkspecs/features/yacc.prf \
		../../qt/5.3/gcc_64/mkspecs/features/lex.prf \
		test.pro \
		/home/lzs/qt/5.3/gcc_64/lib/libQt5Quick.prl \
		/home/lzs/qt/5.3/gcc_64/lib/libQt5Qml.prl \
		/home/lzs/qt/5.3/gcc_64/lib/libQt5Network.prl \
		/home/lzs/qt/5.3/gcc_64/lib/libQt5Core.prl \
		/home/lzs/qt/5.3/gcc_64/lib/libQt5Gui.prl \
		/home/lzs/qt/5.3/gcc_64/lib/libQt5Widgets.prl
	$(QMAKE) -o Makefile test.pro
../../qt/5.3/gcc_64/mkspecs/features/spec_pre.prf:
../../qt/5.3/gcc_64/mkspecs/common/shell-unix.conf:
../../qt/5.3/gcc_64/mkspecs/common/unix.conf:
../../qt/5.3/gcc_64/mkspecs/common/linux.conf:
../../qt/5.3/gcc_64/mkspecs/common/gcc-base.conf:
../../qt/5.3/gcc_64/mkspecs/common/gcc-base-unix.conf:
../../qt/5.3/gcc_64/mkspecs/common/g++-base.conf:
../../qt/5.3/gcc_64/mkspecs/common/g++-unix.conf:
../../qt/5.3/gcc_64/mkspecs/qconfig.pri:
../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_core.pri:
../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_declarative.pri:
../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri:
../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_designer.pri:
../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_enginio.pri:
../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri:
../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_gui.pri:
../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_help.pri:
../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_network.pri:
../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_qml.pri:
../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_quick.pri:
../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_script.pri:
../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_script_private.pri:
../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_sql.pri:
../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_svg.pri:
../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_webkit.pri:
../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri:
../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_xml.pri:
../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../qt/5.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../qt/5.3/gcc_64/mkspecs/features/qt_functions.prf:
../../qt/5.3/gcc_64/mkspecs/features/qt_config.prf:
../../qt/5.3/gcc_64/mkspecs/linux-g++/qmake.conf:
../../qt/5.3/gcc_64/mkspecs/features/spec_post.prf:
../../qt/5.3/gcc_64/mkspecs/features/exclusive_builds.prf:
../../qt/5.3/gcc_64/mkspecs/features/default_pre.prf:
../../qt/5.3/gcc_64/mkspecs/features/resolve_config.prf:
../../qt/5.3/gcc_64/mkspecs/features/default_post.prf:
../../qt/5.3/gcc_64/mkspecs/features/warn_on.prf:
../../qt/5.3/gcc_64/mkspecs/features/qt.prf:
../../qt/5.3/gcc_64/mkspecs/features/resources.prf:
../../qt/5.3/gcc_64/mkspecs/features/moc.prf:
../../qt/5.3/gcc_64/mkspecs/features/unix/opengl.prf:
../../qt/5.3/gcc_64/mkspecs/features/uic.prf:
../../qt/5.3/gcc_64/mkspecs/features/unix/thread.prf:
../../qt/5.3/gcc_64/mkspecs/features/testcase_targets.prf:
../../qt/5.3/gcc_64/mkspecs/features/exceptions.prf:
../../qt/5.3/gcc_64/mkspecs/features/yacc.prf:
../../qt/5.3/gcc_64/mkspecs/features/lex.prf:
test.pro:
/home/lzs/qt/5.3/gcc_64/lib/libQt5Quick.prl:
/home/lzs/qt/5.3/gcc_64/lib/libQt5Qml.prl:
/home/lzs/qt/5.3/gcc_64/lib/libQt5Network.prl:
/home/lzs/qt/5.3/gcc_64/lib/libQt5Core.prl:
/home/lzs/qt/5.3/gcc_64/lib/libQt5Gui.prl:
/home/lzs/qt/5.3/gcc_64/lib/libQt5Widgets.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile test.pro

qmake_all: FORCE

dist: 
	@test -d .tmp/test1.0.0 || mkdir -p .tmp/test1.0.0
	$(COPY_FILE) --parents $(DIST) .tmp/test1.0.0/ && $(COPY_FILE) --parents mainwindow.h mainwindow2.h dia_spd.h .tmp/test1.0.0/ && $(COPY_FILE) --parents mainwindow.cpp mainwindow2.cpp test.cpp dia_spd.cpp .tmp/test1.0.0/ && (cd `dirname .tmp/test1.0.0` && $(TAR) test1.0.0.tar test1.0.0 && $(COMPRESS) test1.0.0.tar) && $(MOVE) `dirname .tmp/test1.0.0`/test1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/test1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_mainwindow.cpp moc_mainwindow2.cpp moc_dia_spd.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_mainwindow2.cpp moc_dia_spd.cpp
moc_mainwindow.cpp: ../../qt/5.3/gcc_64/include/QtWidgets/QMainWindow \
		../../qt/5.3/gcc_64/include/QtWidgets/qmainwindow.h \
		../../qt/5.3/gcc_64/include/QtWidgets/qwidget.h \
		../../qt/5.3/gcc_64/include/QtGui/qwindowdefs.h \
		../../qt/5.3/gcc_64/include/QtCore/qglobal.h \
		../../qt/5.3/gcc_64/include/QtCore/qconfig.h \
		../../qt/5.3/gcc_64/include/QtCore/qfeatures.h \
		../../qt/5.3/gcc_64/include/QtCore/qsystemdetection.h \
		../../qt/5.3/gcc_64/include/QtCore/qprocessordetection.h \
		../../qt/5.3/gcc_64/include/QtCore/qcompilerdetection.h \
		../../qt/5.3/gcc_64/include/QtCore/qtypeinfo.h \
		../../qt/5.3/gcc_64/include/QtCore/qtypetraits.h \
		../../qt/5.3/gcc_64/include/QtCore/qsysinfo.h \
		../../qt/5.3/gcc_64/include/QtCore/qlogging.h \
		../../qt/5.3/gcc_64/include/QtCore/qflags.h \
		../../qt/5.3/gcc_64/include/QtCore/qatomic.h \
		../../qt/5.3/gcc_64/include/QtCore/qbasicatomic.h \
		../../qt/5.3/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../qt/5.3/gcc_64/include/QtCore/qgenericatomic.h \
		../../qt/5.3/gcc_64/include/QtCore/qatomic_msvc.h \
		../../qt/5.3/gcc_64/include/QtCore/qatomic_armv7.h \
		../../qt/5.3/gcc_64/include/QtCore/qatomic_armv6.h \
		../../qt/5.3/gcc_64/include/QtCore/qatomic_armv5.h \
		../../qt/5.3/gcc_64/include/QtCore/qatomic_ia64.h \
		../../qt/5.3/gcc_64/include/QtCore/qatomic_mips.h \
		../../qt/5.3/gcc_64/include/QtCore/qatomic_x86.h \
		../../qt/5.3/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../qt/5.3/gcc_64/include/QtCore/qatomic_gcc.h \
		../../qt/5.3/gcc_64/include/QtCore/qatomic_unix.h \
		../../qt/5.3/gcc_64/include/QtCore/qglobalstatic.h \
		../../qt/5.3/gcc_64/include/QtCore/qmutex.h \
		../../qt/5.3/gcc_64/include/QtCore/qnumeric.h \
		../../qt/5.3/gcc_64/include/QtCore/qobjectdefs.h \
		../../qt/5.3/gcc_64/include/QtCore/qnamespace.h \
		../../qt/5.3/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../qt/5.3/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../qt/5.3/gcc_64/include/QtCore/qobject.h \
		../../qt/5.3/gcc_64/include/QtCore/qstring.h \
		../../qt/5.3/gcc_64/include/QtCore/qchar.h \
		../../qt/5.3/gcc_64/include/QtCore/qbytearray.h \
		../../qt/5.3/gcc_64/include/QtCore/qrefcount.h \
		../../qt/5.3/gcc_64/include/QtCore/qarraydata.h \
		../../qt/5.3/gcc_64/include/QtCore/qstringbuilder.h \
		../../qt/5.3/gcc_64/include/QtCore/qlist.h \
		../../qt/5.3/gcc_64/include/QtCore/qalgorithms.h \
		../../qt/5.3/gcc_64/include/QtCore/qiterator.h \
		../../qt/5.3/gcc_64/include/QtCore/qcoreevent.h \
		../../qt/5.3/gcc_64/include/QtCore/qscopedpointer.h \
		../../qt/5.3/gcc_64/include/QtCore/qmetatype.h \
		../../qt/5.3/gcc_64/include/QtCore/qvarlengtharray.h \
		../../qt/5.3/gcc_64/include/QtCore/qcontainerfwd.h \
		../../qt/5.3/gcc_64/include/QtCore/qisenum.h \
		../../qt/5.3/gcc_64/include/QtCore/qobject_impl.h \
		../../qt/5.3/gcc_64/include/QtCore/qmargins.h \
		../../qt/5.3/gcc_64/include/QtGui/qpaintdevice.h \
		../../qt/5.3/gcc_64/include/QtCore/qrect.h \
		../../qt/5.3/gcc_64/include/QtCore/qsize.h \
		../../qt/5.3/gcc_64/include/QtCore/qpoint.h \
		../../qt/5.3/gcc_64/include/QtGui/qpalette.h \
		../../qt/5.3/gcc_64/include/QtGui/qcolor.h \
		../../qt/5.3/gcc_64/include/QtGui/qrgb.h \
		../../qt/5.3/gcc_64/include/QtCore/qstringlist.h \
		../../qt/5.3/gcc_64/include/QtCore/qdatastream.h \
		../../qt/5.3/gcc_64/include/QtCore/qiodevice.h \
		../../qt/5.3/gcc_64/include/QtCore/qpair.h \
		../../qt/5.3/gcc_64/include/QtCore/qregexp.h \
		../../qt/5.3/gcc_64/include/QtCore/qstringmatcher.h \
		../../qt/5.3/gcc_64/include/QtGui/qbrush.h \
		../../qt/5.3/gcc_64/include/QtCore/qvector.h \
		../../qt/5.3/gcc_64/include/QtGui/qmatrix.h \
		../../qt/5.3/gcc_64/include/QtGui/qpolygon.h \
		../../qt/5.3/gcc_64/include/QtGui/qregion.h \
		../../qt/5.3/gcc_64/include/QtCore/qline.h \
		../../qt/5.3/gcc_64/include/QtGui/qtransform.h \
		../../qt/5.3/gcc_64/include/QtGui/qpainterpath.h \
		../../qt/5.3/gcc_64/include/QtGui/qimage.h \
		../../qt/5.3/gcc_64/include/QtGui/qpixmap.h \
		../../qt/5.3/gcc_64/include/QtCore/qsharedpointer.h \
		../../qt/5.3/gcc_64/include/QtCore/qshareddata.h \
		../../qt/5.3/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../qt/5.3/gcc_64/include/QtCore/qhash.h \
		../../qt/5.3/gcc_64/include/QtGui/qfont.h \
		../../qt/5.3/gcc_64/include/QtGui/qfontmetrics.h \
		../../qt/5.3/gcc_64/include/QtGui/qfontinfo.h \
		../../qt/5.3/gcc_64/include/QtWidgets/qsizepolicy.h \
		../../qt/5.3/gcc_64/include/QtGui/qcursor.h \
		../../qt/5.3/gcc_64/include/QtGui/qkeysequence.h \
		../../qt/5.3/gcc_64/include/QtGui/qevent.h \
		../../qt/5.3/gcc_64/include/QtCore/qvariant.h \
		../../qt/5.3/gcc_64/include/QtCore/qmap.h \
		../../qt/5.3/gcc_64/include/QtCore/qdebug.h \
		../../qt/5.3/gcc_64/include/QtCore/qtextstream.h \
		../../qt/5.3/gcc_64/include/QtCore/qlocale.h \
		../../qt/5.3/gcc_64/include/QtCore/qset.h \
		../../qt/5.3/gcc_64/include/QtCore/qcontiguouscache.h \
		../../qt/5.3/gcc_64/include/QtCore/qurl.h \
		../../qt/5.3/gcc_64/include/QtCore/qurlquery.h \
		../../qt/5.3/gcc_64/include/QtCore/qfile.h \
		../../qt/5.3/gcc_64/include/QtCore/qfiledevice.h \
		../../qt/5.3/gcc_64/include/QtGui/qvector2d.h \
		../../qt/5.3/gcc_64/include/QtGui/qtouchdevice.h \
		../../qt/5.3/gcc_64/include/QtWidgets/qtabwidget.h \
		../../qt/5.3/gcc_64/include/QtGui/qicon.h \
		../../qt/5.3/gcc_64/include/QtWidgets/QApplication \
		../../qt/5.3/gcc_64/include/QtWidgets/qapplication.h \
		../../qt/5.3/gcc_64/include/QtCore/qcoreapplication.h \
		../../qt/5.3/gcc_64/include/QtCore/qeventloop.h \
		../../qt/5.3/gcc_64/include/QtWidgets/qdesktopwidget.h \
		../../qt/5.3/gcc_64/include/QtGui/qguiapplication.h \
		../../qt/5.3/gcc_64/include/QtGui/qinputmethod.h \
		../../qt/5.3/gcc_64/include/QtWidgets/QAction \
		../../qt/5.3/gcc_64/include/QtWidgets/qaction.h \
		../../qt/5.3/gcc_64/include/QtWidgets/qactiongroup.h \
		../../qt/5.3/gcc_64/include/QtWidgets/QMenu \
		../../qt/5.3/gcc_64/include/QtWidgets/qmenu.h \
		../../qt/5.3/gcc_64/include/QtWidgets/QFileDialog \
		../../qt/5.3/gcc_64/include/QtWidgets/qfiledialog.h \
		../../qt/5.3/gcc_64/include/QtCore/qdir.h \
		../../qt/5.3/gcc_64/include/QtCore/qfileinfo.h \
		../../qt/5.3/gcc_64/include/QtWidgets/qdialog.h \
		../../qt/5.3/gcc_64/include/QtCore/QFile \
		../../qt/5.3/gcc_64/include/QtCore/QTextStream \
		../../qt/5.3/gcc_64/include/QtWidgets/QToolBar \
		../../qt/5.3/gcc_64/include/QtWidgets/qtoolbar.h \
		../../qt/5.3/gcc_64/include/QtWidgets/QTextEdit \
		../../qt/5.3/gcc_64/include/QtWidgets/qtextedit.h \
		../../qt/5.3/gcc_64/include/QtWidgets/qabstractscrollarea.h \
		../../qt/5.3/gcc_64/include/QtWidgets/qframe.h \
		../../qt/5.3/gcc_64/include/QtGui/qtextdocument.h \
		../../qt/5.3/gcc_64/include/QtGui/qtextoption.h \
		../../qt/5.3/gcc_64/include/QtGui/qtextcursor.h \
		../../qt/5.3/gcc_64/include/QtGui/qtextformat.h \
		../../qt/5.3/gcc_64/include/QtGui/qpen.h \
		../../qt/5.3/gcc_64/include/QtCore/QString \
		../../qt/5.3/gcc_64/include/QtWidgets/QMenuBar \
		../../qt/5.3/gcc_64/include/QtWidgets/qmenubar.h \
		../../qt/5.3/gcc_64/include/QtGui/QMouseEvent \
		../../qt/5.3/gcc_64/include/QtWidgets/QPushButton \
		../../qt/5.3/gcc_64/include/QtWidgets/qpushbutton.h \
		../../qt/5.3/gcc_64/include/QtWidgets/qabstractbutton.h \
		../../qt/5.3/gcc_64/include/QtWidgets/QLabel \
		../../qt/5.3/gcc_64/include/QtWidgets/qlabel.h \
		../../qt/5.3/gcc_64/include/QtWidgets/QLineEdit \
		../../qt/5.3/gcc_64/include/QtWidgets/qlineedit.h \
		../../qt/5.3/gcc_64/include/QtWidgets/QMessageBox \
		../../qt/5.3/gcc_64/include/QtWidgets/qmessagebox.h \
		mainwindow2.h \
		dia_spd.h \
		../../qt/5.3/gcc_64/include/QtWidgets/QDialog \
		../../qt/5.3/gcc_64/include/QtWidgets/QVBoxLayout \
		../../qt/5.3/gcc_64/include/QtWidgets/qboxlayout.h \
		../../qt/5.3/gcc_64/include/QtWidgets/qlayout.h \
		../../qt/5.3/gcc_64/include/QtWidgets/qlayoutitem.h \
		../../qt/5.3/gcc_64/include/QtWidgets/qgridlayout.h \
		mainwindow.h
	/home/lzs/qt/5.3/gcc_64/bin/moc $(DEFINES) -I/home/lzs/qt/5.3/gcc_64/mkspecs/linux-g++ -I/home/lzs/test/spd -I/home/lzs/test/spd -I/home/lzs/qt/5.3/gcc_64/include -I/home/lzs/qt/5.3/gcc_64/include/QtQuick -I/home/lzs/qt/5.3/gcc_64/include/QtQml -I/home/lzs/qt/5.3/gcc_64/include/QtWidgets -I/home/lzs/qt/5.3/gcc_64/include/QtNetwork -I/home/lzs/qt/5.3/gcc_64/include/QtGui -I/home/lzs/qt/5.3/gcc_64/include/QtCore mainwindow.h -o moc_mainwindow.cpp

moc_mainwindow2.cpp: ../../qt/5.3/gcc_64/include/QtWidgets/QMainWindow \
		../../qt/5.3/gcc_64/include/QtWidgets/qmainwindow.h \
		../../qt/5.3/gcc_64/include/QtWidgets/qwidget.h \
		../../qt/5.3/gcc_64/include/QtGui/qwindowdefs.h \
		../../qt/5.3/gcc_64/include/QtCore/qglobal.h \
		../../qt/5.3/gcc_64/include/QtCore/qconfig.h \
		../../qt/5.3/gcc_64/include/QtCore/qfeatures.h \
		../../qt/5.3/gcc_64/include/QtCore/qsystemdetection.h \
		../../qt/5.3/gcc_64/include/QtCore/qprocessordetection.h \
		../../qt/5.3/gcc_64/include/QtCore/qcompilerdetection.h \
		../../qt/5.3/gcc_64/include/QtCore/qtypeinfo.h \
		../../qt/5.3/gcc_64/include/QtCore/qtypetraits.h \
		../../qt/5.3/gcc_64/include/QtCore/qsysinfo.h \
		../../qt/5.3/gcc_64/include/QtCore/qlogging.h \
		../../qt/5.3/gcc_64/include/QtCore/qflags.h \
		../../qt/5.3/gcc_64/include/QtCore/qatomic.h \
		../../qt/5.3/gcc_64/include/QtCore/qbasicatomic.h \
		../../qt/5.3/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../qt/5.3/gcc_64/include/QtCore/qgenericatomic.h \
		../../qt/5.3/gcc_64/include/QtCore/qatomic_msvc.h \
		../../qt/5.3/gcc_64/include/QtCore/qatomic_armv7.h \
		../../qt/5.3/gcc_64/include/QtCore/qatomic_armv6.h \
		../../qt/5.3/gcc_64/include/QtCore/qatomic_armv5.h \
		../../qt/5.3/gcc_64/include/QtCore/qatomic_ia64.h \
		../../qt/5.3/gcc_64/include/QtCore/qatomic_mips.h \
		../../qt/5.3/gcc_64/include/QtCore/qatomic_x86.h \
		../../qt/5.3/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../qt/5.3/gcc_64/include/QtCore/qatomic_gcc.h \
		../../qt/5.3/gcc_64/include/QtCore/qatomic_unix.h \
		../../qt/5.3/gcc_64/include/QtCore/qglobalstatic.h \
		../../qt/5.3/gcc_64/include/QtCore/qmutex.h \
		../../qt/5.3/gcc_64/include/QtCore/qnumeric.h \
		../../qt/5.3/gcc_64/include/QtCore/qobjectdefs.h \
		../../qt/5.3/gcc_64/include/QtCore/qnamespace.h \
		../../qt/5.3/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../qt/5.3/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../qt/5.3/gcc_64/include/QtCore/qobject.h \
		../../qt/5.3/gcc_64/include/QtCore/qstring.h \
		../../qt/5.3/gcc_64/include/QtCore/qchar.h \
		../../qt/5.3/gcc_64/include/QtCore/qbytearray.h \
		../../qt/5.3/gcc_64/include/QtCore/qrefcount.h \
		../../qt/5.3/gcc_64/include/QtCore/qarraydata.h \
		../../qt/5.3/gcc_64/include/QtCore/qstringbuilder.h \
		../../qt/5.3/gcc_64/include/QtCore/qlist.h \
		../../qt/5.3/gcc_64/include/QtCore/qalgorithms.h \
		../../qt/5.3/gcc_64/include/QtCore/qiterator.h \
		../../qt/5.3/gcc_64/include/QtCore/qcoreevent.h \
		../../qt/5.3/gcc_64/include/QtCore/qscopedpointer.h \
		../../qt/5.3/gcc_64/include/QtCore/qmetatype.h \
		../../qt/5.3/gcc_64/include/QtCore/qvarlengtharray.h \
		../../qt/5.3/gcc_64/include/QtCore/qcontainerfwd.h \
		../../qt/5.3/gcc_64/include/QtCore/qisenum.h \
		../../qt/5.3/gcc_64/include/QtCore/qobject_impl.h \
		../../qt/5.3/gcc_64/include/QtCore/qmargins.h \
		../../qt/5.3/gcc_64/include/QtGui/qpaintdevice.h \
		../../qt/5.3/gcc_64/include/QtCore/qrect.h \
		../../qt/5.3/gcc_64/include/QtCore/qsize.h \
		../../qt/5.3/gcc_64/include/QtCore/qpoint.h \
		../../qt/5.3/gcc_64/include/QtGui/qpalette.h \
		../../qt/5.3/gcc_64/include/QtGui/qcolor.h \
		../../qt/5.3/gcc_64/include/QtGui/qrgb.h \
		../../qt/5.3/gcc_64/include/QtCore/qstringlist.h \
		../../qt/5.3/gcc_64/include/QtCore/qdatastream.h \
		../../qt/5.3/gcc_64/include/QtCore/qiodevice.h \
		../../qt/5.3/gcc_64/include/QtCore/qpair.h \
		../../qt/5.3/gcc_64/include/QtCore/qregexp.h \
		../../qt/5.3/gcc_64/include/QtCore/qstringmatcher.h \
		../../qt/5.3/gcc_64/include/QtGui/qbrush.h \
		../../qt/5.3/gcc_64/include/QtCore/qvector.h \
		../../qt/5.3/gcc_64/include/QtGui/qmatrix.h \
		../../qt/5.3/gcc_64/include/QtGui/qpolygon.h \
		../../qt/5.3/gcc_64/include/QtGui/qregion.h \
		../../qt/5.3/gcc_64/include/QtCore/qline.h \
		../../qt/5.3/gcc_64/include/QtGui/qtransform.h \
		../../qt/5.3/gcc_64/include/QtGui/qpainterpath.h \
		../../qt/5.3/gcc_64/include/QtGui/qimage.h \
		../../qt/5.3/gcc_64/include/QtGui/qpixmap.h \
		../../qt/5.3/gcc_64/include/QtCore/qsharedpointer.h \
		../../qt/5.3/gcc_64/include/QtCore/qshareddata.h \
		../../qt/5.3/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../qt/5.3/gcc_64/include/QtCore/qhash.h \
		../../qt/5.3/gcc_64/include/QtGui/qfont.h \
		../../qt/5.3/gcc_64/include/QtGui/qfontmetrics.h \
		../../qt/5.3/gcc_64/include/QtGui/qfontinfo.h \
		../../qt/5.3/gcc_64/include/QtWidgets/qsizepolicy.h \
		../../qt/5.3/gcc_64/include/QtGui/qcursor.h \
		../../qt/5.3/gcc_64/include/QtGui/qkeysequence.h \
		../../qt/5.3/gcc_64/include/QtGui/qevent.h \
		../../qt/5.3/gcc_64/include/QtCore/qvariant.h \
		../../qt/5.3/gcc_64/include/QtCore/qmap.h \
		../../qt/5.3/gcc_64/include/QtCore/qdebug.h \
		../../qt/5.3/gcc_64/include/QtCore/qtextstream.h \
		../../qt/5.3/gcc_64/include/QtCore/qlocale.h \
		../../qt/5.3/gcc_64/include/QtCore/qset.h \
		../../qt/5.3/gcc_64/include/QtCore/qcontiguouscache.h \
		../../qt/5.3/gcc_64/include/QtCore/qurl.h \
		../../qt/5.3/gcc_64/include/QtCore/qurlquery.h \
		../../qt/5.3/gcc_64/include/QtCore/qfile.h \
		../../qt/5.3/gcc_64/include/QtCore/qfiledevice.h \
		../../qt/5.3/gcc_64/include/QtGui/qvector2d.h \
		../../qt/5.3/gcc_64/include/QtGui/qtouchdevice.h \
		../../qt/5.3/gcc_64/include/QtWidgets/qtabwidget.h \
		../../qt/5.3/gcc_64/include/QtGui/qicon.h \
		../../qt/5.3/gcc_64/include/QtWidgets/QApplication \
		../../qt/5.3/gcc_64/include/QtWidgets/qapplication.h \
		../../qt/5.3/gcc_64/include/QtCore/qcoreapplication.h \
		../../qt/5.3/gcc_64/include/QtCore/qeventloop.h \
		../../qt/5.3/gcc_64/include/QtWidgets/qdesktopwidget.h \
		../../qt/5.3/gcc_64/include/QtGui/qguiapplication.h \
		../../qt/5.3/gcc_64/include/QtGui/qinputmethod.h \
		../../qt/5.3/gcc_64/include/QtWidgets/QAction \
		../../qt/5.3/gcc_64/include/QtWidgets/qaction.h \
		../../qt/5.3/gcc_64/include/QtWidgets/qactiongroup.h \
		../../qt/5.3/gcc_64/include/QtWidgets/QMenu \
		../../qt/5.3/gcc_64/include/QtWidgets/qmenu.h \
		../../qt/5.3/gcc_64/include/QtWidgets/QFileDialog \
		../../qt/5.3/gcc_64/include/QtWidgets/qfiledialog.h \
		../../qt/5.3/gcc_64/include/QtCore/qdir.h \
		../../qt/5.3/gcc_64/include/QtCore/qfileinfo.h \
		../../qt/5.3/gcc_64/include/QtWidgets/qdialog.h \
		../../qt/5.3/gcc_64/include/QtCore/QFile \
		../../qt/5.3/gcc_64/include/QtCore/QTextStream \
		../../qt/5.3/gcc_64/include/QtWidgets/QToolBar \
		../../qt/5.3/gcc_64/include/QtWidgets/qtoolbar.h \
		../../qt/5.3/gcc_64/include/QtWidgets/QTextEdit \
		../../qt/5.3/gcc_64/include/QtWidgets/qtextedit.h \
		../../qt/5.3/gcc_64/include/QtWidgets/qabstractscrollarea.h \
		../../qt/5.3/gcc_64/include/QtWidgets/qframe.h \
		../../qt/5.3/gcc_64/include/QtGui/qtextdocument.h \
		../../qt/5.3/gcc_64/include/QtGui/qtextoption.h \
		../../qt/5.3/gcc_64/include/QtGui/qtextcursor.h \
		../../qt/5.3/gcc_64/include/QtGui/qtextformat.h \
		../../qt/5.3/gcc_64/include/QtGui/qpen.h \
		../../qt/5.3/gcc_64/include/QtCore/QString \
		../../qt/5.3/gcc_64/include/QtWidgets/QMenuBar \
		../../qt/5.3/gcc_64/include/QtWidgets/qmenubar.h \
		../../qt/5.3/gcc_64/include/QtGui/QMouseEvent \
		../../qt/5.3/gcc_64/include/QtWidgets/QPushButton \
		../../qt/5.3/gcc_64/include/QtWidgets/qpushbutton.h \
		../../qt/5.3/gcc_64/include/QtWidgets/qabstractbutton.h \
		dia_spd.h \
		../../qt/5.3/gcc_64/include/QtWidgets/QDialog \
		../../qt/5.3/gcc_64/include/QtWidgets/QVBoxLayout \
		../../qt/5.3/gcc_64/include/QtWidgets/qboxlayout.h \
		../../qt/5.3/gcc_64/include/QtWidgets/qlayout.h \
		../../qt/5.3/gcc_64/include/QtWidgets/qlayoutitem.h \
		../../qt/5.3/gcc_64/include/QtWidgets/qgridlayout.h \
		mainwindow2.h
	/home/lzs/qt/5.3/gcc_64/bin/moc $(DEFINES) -I/home/lzs/qt/5.3/gcc_64/mkspecs/linux-g++ -I/home/lzs/test/spd -I/home/lzs/test/spd -I/home/lzs/qt/5.3/gcc_64/include -I/home/lzs/qt/5.3/gcc_64/include/QtQuick -I/home/lzs/qt/5.3/gcc_64/include/QtQml -I/home/lzs/qt/5.3/gcc_64/include/QtWidgets -I/home/lzs/qt/5.3/gcc_64/include/QtNetwork -I/home/lzs/qt/5.3/gcc_64/include/QtGui -I/home/lzs/qt/5.3/gcc_64/include/QtCore mainwindow2.h -o moc_mainwindow2.cpp

moc_dia_spd.cpp: ../../qt/5.3/gcc_64/include/QtWidgets/QDialog \
		../../qt/5.3/gcc_64/include/QtWidgets/qdialog.h \
		../../qt/5.3/gcc_64/include/QtWidgets/qwidget.h \
		../../qt/5.3/gcc_64/include/QtGui/qwindowdefs.h \
		../../qt/5.3/gcc_64/include/QtCore/qglobal.h \
		../../qt/5.3/gcc_64/include/QtCore/qconfig.h \
		../../qt/5.3/gcc_64/include/QtCore/qfeatures.h \
		../../qt/5.3/gcc_64/include/QtCore/qsystemdetection.h \
		../../qt/5.3/gcc_64/include/QtCore/qprocessordetection.h \
		../../qt/5.3/gcc_64/include/QtCore/qcompilerdetection.h \
		../../qt/5.3/gcc_64/include/QtCore/qtypeinfo.h \
		../../qt/5.3/gcc_64/include/QtCore/qtypetraits.h \
		../../qt/5.3/gcc_64/include/QtCore/qsysinfo.h \
		../../qt/5.3/gcc_64/include/QtCore/qlogging.h \
		../../qt/5.3/gcc_64/include/QtCore/qflags.h \
		../../qt/5.3/gcc_64/include/QtCore/qatomic.h \
		../../qt/5.3/gcc_64/include/QtCore/qbasicatomic.h \
		../../qt/5.3/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../qt/5.3/gcc_64/include/QtCore/qgenericatomic.h \
		../../qt/5.3/gcc_64/include/QtCore/qatomic_msvc.h \
		../../qt/5.3/gcc_64/include/QtCore/qatomic_armv7.h \
		../../qt/5.3/gcc_64/include/QtCore/qatomic_armv6.h \
		../../qt/5.3/gcc_64/include/QtCore/qatomic_armv5.h \
		../../qt/5.3/gcc_64/include/QtCore/qatomic_ia64.h \
		../../qt/5.3/gcc_64/include/QtCore/qatomic_mips.h \
		../../qt/5.3/gcc_64/include/QtCore/qatomic_x86.h \
		../../qt/5.3/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../qt/5.3/gcc_64/include/QtCore/qatomic_gcc.h \
		../../qt/5.3/gcc_64/include/QtCore/qatomic_unix.h \
		../../qt/5.3/gcc_64/include/QtCore/qglobalstatic.h \
		../../qt/5.3/gcc_64/include/QtCore/qmutex.h \
		../../qt/5.3/gcc_64/include/QtCore/qnumeric.h \
		../../qt/5.3/gcc_64/include/QtCore/qobjectdefs.h \
		../../qt/5.3/gcc_64/include/QtCore/qnamespace.h \
		../../qt/5.3/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../qt/5.3/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../qt/5.3/gcc_64/include/QtCore/qobject.h \
		../../qt/5.3/gcc_64/include/QtCore/qstring.h \
		../../qt/5.3/gcc_64/include/QtCore/qchar.h \
		../../qt/5.3/gcc_64/include/QtCore/qbytearray.h \
		../../qt/5.3/gcc_64/include/QtCore/qrefcount.h \
		../../qt/5.3/gcc_64/include/QtCore/qarraydata.h \
		../../qt/5.3/gcc_64/include/QtCore/qstringbuilder.h \
		../../qt/5.3/gcc_64/include/QtCore/qlist.h \
		../../qt/5.3/gcc_64/include/QtCore/qalgorithms.h \
		../../qt/5.3/gcc_64/include/QtCore/qiterator.h \
		../../qt/5.3/gcc_64/include/QtCore/qcoreevent.h \
		../../qt/5.3/gcc_64/include/QtCore/qscopedpointer.h \
		../../qt/5.3/gcc_64/include/QtCore/qmetatype.h \
		../../qt/5.3/gcc_64/include/QtCore/qvarlengtharray.h \
		../../qt/5.3/gcc_64/include/QtCore/qcontainerfwd.h \
		../../qt/5.3/gcc_64/include/QtCore/qisenum.h \
		../../qt/5.3/gcc_64/include/QtCore/qobject_impl.h \
		../../qt/5.3/gcc_64/include/QtCore/qmargins.h \
		../../qt/5.3/gcc_64/include/QtGui/qpaintdevice.h \
		../../qt/5.3/gcc_64/include/QtCore/qrect.h \
		../../qt/5.3/gcc_64/include/QtCore/qsize.h \
		../../qt/5.3/gcc_64/include/QtCore/qpoint.h \
		../../qt/5.3/gcc_64/include/QtGui/qpalette.h \
		../../qt/5.3/gcc_64/include/QtGui/qcolor.h \
		../../qt/5.3/gcc_64/include/QtGui/qrgb.h \
		../../qt/5.3/gcc_64/include/QtCore/qstringlist.h \
		../../qt/5.3/gcc_64/include/QtCore/qdatastream.h \
		../../qt/5.3/gcc_64/include/QtCore/qiodevice.h \
		../../qt/5.3/gcc_64/include/QtCore/qpair.h \
		../../qt/5.3/gcc_64/include/QtCore/qregexp.h \
		../../qt/5.3/gcc_64/include/QtCore/qstringmatcher.h \
		../../qt/5.3/gcc_64/include/QtGui/qbrush.h \
		../../qt/5.3/gcc_64/include/QtCore/qvector.h \
		../../qt/5.3/gcc_64/include/QtGui/qmatrix.h \
		../../qt/5.3/gcc_64/include/QtGui/qpolygon.h \
		../../qt/5.3/gcc_64/include/QtGui/qregion.h \
		../../qt/5.3/gcc_64/include/QtCore/qline.h \
		../../qt/5.3/gcc_64/include/QtGui/qtransform.h \
		../../qt/5.3/gcc_64/include/QtGui/qpainterpath.h \
		../../qt/5.3/gcc_64/include/QtGui/qimage.h \
		../../qt/5.3/gcc_64/include/QtGui/qpixmap.h \
		../../qt/5.3/gcc_64/include/QtCore/qsharedpointer.h \
		../../qt/5.3/gcc_64/include/QtCore/qshareddata.h \
		../../qt/5.3/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../qt/5.3/gcc_64/include/QtCore/qhash.h \
		../../qt/5.3/gcc_64/include/QtGui/qfont.h \
		../../qt/5.3/gcc_64/include/QtGui/qfontmetrics.h \
		../../qt/5.3/gcc_64/include/QtGui/qfontinfo.h \
		../../qt/5.3/gcc_64/include/QtWidgets/qsizepolicy.h \
		../../qt/5.3/gcc_64/include/QtGui/qcursor.h \
		../../qt/5.3/gcc_64/include/QtGui/qkeysequence.h \
		../../qt/5.3/gcc_64/include/QtGui/qevent.h \
		../../qt/5.3/gcc_64/include/QtCore/qvariant.h \
		../../qt/5.3/gcc_64/include/QtCore/qmap.h \
		../../qt/5.3/gcc_64/include/QtCore/qdebug.h \
		../../qt/5.3/gcc_64/include/QtCore/qtextstream.h \
		../../qt/5.3/gcc_64/include/QtCore/qlocale.h \
		../../qt/5.3/gcc_64/include/QtCore/qset.h \
		../../qt/5.3/gcc_64/include/QtCore/qcontiguouscache.h \
		../../qt/5.3/gcc_64/include/QtCore/qurl.h \
		../../qt/5.3/gcc_64/include/QtCore/qurlquery.h \
		../../qt/5.3/gcc_64/include/QtCore/qfile.h \
		../../qt/5.3/gcc_64/include/QtCore/qfiledevice.h \
		../../qt/5.3/gcc_64/include/QtGui/qvector2d.h \
		../../qt/5.3/gcc_64/include/QtGui/qtouchdevice.h \
		../../qt/5.3/gcc_64/include/QtWidgets/QPushButton \
		../../qt/5.3/gcc_64/include/QtWidgets/qpushbutton.h \
		../../qt/5.3/gcc_64/include/QtWidgets/qabstractbutton.h \
		../../qt/5.3/gcc_64/include/QtGui/qicon.h \
		../../qt/5.3/gcc_64/include/QtWidgets/QVBoxLayout \
		../../qt/5.3/gcc_64/include/QtWidgets/qboxlayout.h \
		../../qt/5.3/gcc_64/include/QtWidgets/qlayout.h \
		../../qt/5.3/gcc_64/include/QtWidgets/qlayoutitem.h \
		../../qt/5.3/gcc_64/include/QtWidgets/qgridlayout.h \
		dia_spd.h
	/home/lzs/qt/5.3/gcc_64/bin/moc $(DEFINES) -I/home/lzs/qt/5.3/gcc_64/mkspecs/linux-g++ -I/home/lzs/test/spd -I/home/lzs/test/spd -I/home/lzs/qt/5.3/gcc_64/include -I/home/lzs/qt/5.3/gcc_64/include/QtQuick -I/home/lzs/qt/5.3/gcc_64/include/QtQml -I/home/lzs/qt/5.3/gcc_64/include/QtWidgets -I/home/lzs/qt/5.3/gcc_64/include/QtNetwork -I/home/lzs/qt/5.3/gcc_64/include/QtGui -I/home/lzs/qt/5.3/gcc_64/include/QtCore dia_spd.h -o moc_dia_spd.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

mainwindow.o: mainwindow.cpp mainwindow.h \
		../../qt/5.3/gcc_64/include/QtWidgets/QMainWindow \
		../../qt/5.3/gcc_64/include/QtWidgets/qmainwindow.h \
		../../qt/5.3/gcc_64/include/QtWidgets/qwidget.h \
		../../qt/5.3/gcc_64/include/QtGui/qwindowdefs.h \
		../../qt/5.3/gcc_64/include/QtCore/qglobal.h \
		../../qt/5.3/gcc_64/include/QtCore/qconfig.h \
		../../qt/5.3/gcc_64/include/QtCore/qfeatures.h \
		../../qt/5.3/gcc_64/include/QtCore/qsystemdetection.h \
		../../qt/5.3/gcc_64/include/QtCore/qprocessordetection.h \
		../../qt/5.3/gcc_64/include/QtCore/qcompilerdetection.h \
		../../qt/5.3/gcc_64/include/QtCore/qtypeinfo.h \
		../../qt/5.3/gcc_64/include/QtCore/qtypetraits.h \
		../../qt/5.3/gcc_64/include/QtCore/qsysinfo.h \
		../../qt/5.3/gcc_64/include/QtCore/qlogging.h \
		../../qt/5.3/gcc_64/include/QtCore/qflags.h \
		../../qt/5.3/gcc_64/include/QtCore/qatomic.h \
		../../qt/5.3/gcc_64/include/QtCore/qbasicatomic.h \
		../../qt/5.3/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../qt/5.3/gcc_64/include/QtCore/qgenericatomic.h \
		../../qt/5.3/gcc_64/include/QtCore/qatomic_msvc.h \
		../../qt/5.3/gcc_64/include/QtCore/qatomic_armv7.h \
		../../qt/5.3/gcc_64/include/QtCore/qatomic_armv6.h \
		../../qt/5.3/gcc_64/include/QtCore/qatomic_armv5.h \
		../../qt/5.3/gcc_64/include/QtCore/qatomic_ia64.h \
		../../qt/5.3/gcc_64/include/QtCore/qatomic_mips.h \
		../../qt/5.3/gcc_64/include/QtCore/qatomic_x86.h \
		../../qt/5.3/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../qt/5.3/gcc_64/include/QtCore/qatomic_gcc.h \
		../../qt/5.3/gcc_64/include/QtCore/qatomic_unix.h \
		../../qt/5.3/gcc_64/include/QtCore/qglobalstatic.h \
		../../qt/5.3/gcc_64/include/QtCore/qmutex.h \
		../../qt/5.3/gcc_64/include/QtCore/qnumeric.h \
		../../qt/5.3/gcc_64/include/QtCore/qobjectdefs.h \
		../../qt/5.3/gcc_64/include/QtCore/qnamespace.h \
		../../qt/5.3/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../qt/5.3/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../qt/5.3/gcc_64/include/QtCore/qobject.h \
		../../qt/5.3/gcc_64/include/QtCore/qstring.h \
		../../qt/5.3/gcc_64/include/QtCore/qchar.h \
		../../qt/5.3/gcc_64/include/QtCore/qbytearray.h \
		../../qt/5.3/gcc_64/include/QtCore/qrefcount.h \
		../../qt/5.3/gcc_64/include/QtCore/qarraydata.h \
		../../qt/5.3/gcc_64/include/QtCore/qstringbuilder.h \
		../../qt/5.3/gcc_64/include/QtCore/qlist.h \
		../../qt/5.3/gcc_64/include/QtCore/qalgorithms.h \
		../../qt/5.3/gcc_64/include/QtCore/qiterator.h \
		../../qt/5.3/gcc_64/include/QtCore/qcoreevent.h \
		../../qt/5.3/gcc_64/include/QtCore/qscopedpointer.h \
		../../qt/5.3/gcc_64/include/QtCore/qmetatype.h \
		../../qt/5.3/gcc_64/include/QtCore/qvarlengtharray.h \
		../../qt/5.3/gcc_64/include/QtCore/qcontainerfwd.h \
		../../qt/5.3/gcc_64/include/QtCore/qisenum.h \
		../../qt/5.3/gcc_64/include/QtCore/qobject_impl.h \
		../../qt/5.3/gcc_64/include/QtCore/qmargins.h \
		../../qt/5.3/gcc_64/include/QtGui/qpaintdevice.h \
		../../qt/5.3/gcc_64/include/QtCore/qrect.h \
		../../qt/5.3/gcc_64/include/QtCore/qsize.h \
		../../qt/5.3/gcc_64/include/QtCore/qpoint.h \
		../../qt/5.3/gcc_64/include/QtGui/qpalette.h \
		../../qt/5.3/gcc_64/include/QtGui/qcolor.h \
		../../qt/5.3/gcc_64/include/QtGui/qrgb.h \
		../../qt/5.3/gcc_64/include/QtCore/qstringlist.h \
		../../qt/5.3/gcc_64/include/QtCore/qdatastream.h \
		../../qt/5.3/gcc_64/include/QtCore/qiodevice.h \
		../../qt/5.3/gcc_64/include/QtCore/qpair.h \
		../../qt/5.3/gcc_64/include/QtCore/qregexp.h \
		../../qt/5.3/gcc_64/include/QtCore/qstringmatcher.h \
		../../qt/5.3/gcc_64/include/QtGui/qbrush.h \
		../../qt/5.3/gcc_64/include/QtCore/qvector.h \
		../../qt/5.3/gcc_64/include/QtGui/qmatrix.h \
		../../qt/5.3/gcc_64/include/QtGui/qpolygon.h \
		../../qt/5.3/gcc_64/include/QtGui/qregion.h \
		../../qt/5.3/gcc_64/include/QtCore/qline.h \
		../../qt/5.3/gcc_64/include/QtGui/qtransform.h \
		../../qt/5.3/gcc_64/include/QtGui/qpainterpath.h \
		../../qt/5.3/gcc_64/include/QtGui/qimage.h \
		../../qt/5.3/gcc_64/include/QtGui/qpixmap.h \
		../../qt/5.3/gcc_64/include/QtCore/qsharedpointer.h \
		../../qt/5.3/gcc_64/include/QtCore/qshareddata.h \
		../../qt/5.3/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../qt/5.3/gcc_64/include/QtCore/qhash.h \
		../../qt/5.3/gcc_64/include/QtGui/qfont.h \
		../../qt/5.3/gcc_64/include/QtGui/qfontmetrics.h \
		../../qt/5.3/gcc_64/include/QtGui/qfontinfo.h \
		../../qt/5.3/gcc_64/include/QtWidgets/qsizepolicy.h \
		../../qt/5.3/gcc_64/include/QtGui/qcursor.h \
		../../qt/5.3/gcc_64/include/QtGui/qkeysequence.h \
		../../qt/5.3/gcc_64/include/QtGui/qevent.h \
		../../qt/5.3/gcc_64/include/QtCore/qvariant.h \
		../../qt/5.3/gcc_64/include/QtCore/qmap.h \
		../../qt/5.3/gcc_64/include/QtCore/qdebug.h \
		../../qt/5.3/gcc_64/include/QtCore/qtextstream.h \
		../../qt/5.3/gcc_64/include/QtCore/qlocale.h \
		../../qt/5.3/gcc_64/include/QtCore/qset.h \
		../../qt/5.3/gcc_64/include/QtCore/qcontiguouscache.h \
		../../qt/5.3/gcc_64/include/QtCore/qurl.h \
		../../qt/5.3/gcc_64/include/QtCore/qurlquery.h \
		../../qt/5.3/gcc_64/include/QtCore/qfile.h \
		../../qt/5.3/gcc_64/include/QtCore/qfiledevice.h \
		../../qt/5.3/gcc_64/include/QtGui/qvector2d.h \
		../../qt/5.3/gcc_64/include/QtGui/qtouchdevice.h \
		../../qt/5.3/gcc_64/include/QtWidgets/qtabwidget.h \
		../../qt/5.3/gcc_64/include/QtGui/qicon.h \
		../../qt/5.3/gcc_64/include/QtWidgets/QApplication \
		../../qt/5.3/gcc_64/include/QtWidgets/qapplication.h \
		../../qt/5.3/gcc_64/include/QtCore/qcoreapplication.h \
		../../qt/5.3/gcc_64/include/QtCore/qeventloop.h \
		../../qt/5.3/gcc_64/include/QtWidgets/qdesktopwidget.h \
		../../qt/5.3/gcc_64/include/QtGui/qguiapplication.h \
		../../qt/5.3/gcc_64/include/QtGui/qinputmethod.h \
		../../qt/5.3/gcc_64/include/QtWidgets/QAction \
		../../qt/5.3/gcc_64/include/QtWidgets/qaction.h \
		../../qt/5.3/gcc_64/include/QtWidgets/qactiongroup.h \
		../../qt/5.3/gcc_64/include/QtWidgets/QMenu \
		../../qt/5.3/gcc_64/include/QtWidgets/qmenu.h \
		../../qt/5.3/gcc_64/include/QtWidgets/QFileDialog \
		../../qt/5.3/gcc_64/include/QtWidgets/qfiledialog.h \
		../../qt/5.3/gcc_64/include/QtCore/qdir.h \
		../../qt/5.3/gcc_64/include/QtCore/qfileinfo.h \
		../../qt/5.3/gcc_64/include/QtWidgets/qdialog.h \
		../../qt/5.3/gcc_64/include/QtCore/QFile \
		../../qt/5.3/gcc_64/include/QtCore/QTextStream \
		../../qt/5.3/gcc_64/include/QtWidgets/QToolBar \
		../../qt/5.3/gcc_64/include/QtWidgets/qtoolbar.h \
		../../qt/5.3/gcc_64/include/QtWidgets/QTextEdit \
		../../qt/5.3/gcc_64/include/QtWidgets/qtextedit.h \
		../../qt/5.3/gcc_64/include/QtWidgets/qabstractscrollarea.h \
		../../qt/5.3/gcc_64/include/QtWidgets/qframe.h \
		../../qt/5.3/gcc_64/include/QtGui/qtextdocument.h \
		../../qt/5.3/gcc_64/include/QtGui/qtextoption.h \
		../../qt/5.3/gcc_64/include/QtGui/qtextcursor.h \
		../../qt/5.3/gcc_64/include/QtGui/qtextformat.h \
		../../qt/5.3/gcc_64/include/QtGui/qpen.h \
		../../qt/5.3/gcc_64/include/QtCore/QString \
		../../qt/5.3/gcc_64/include/QtWidgets/QMenuBar \
		../../qt/5.3/gcc_64/include/QtWidgets/qmenubar.h \
		../../qt/5.3/gcc_64/include/QtGui/QMouseEvent \
		../../qt/5.3/gcc_64/include/QtWidgets/QPushButton \
		../../qt/5.3/gcc_64/include/QtWidgets/qpushbutton.h \
		../../qt/5.3/gcc_64/include/QtWidgets/qabstractbutton.h \
		../../qt/5.3/gcc_64/include/QtWidgets/QLabel \
		../../qt/5.3/gcc_64/include/QtWidgets/qlabel.h \
		../../qt/5.3/gcc_64/include/QtWidgets/QLineEdit \
		../../qt/5.3/gcc_64/include/QtWidgets/qlineedit.h \
		../../qt/5.3/gcc_64/include/QtWidgets/QMessageBox \
		../../qt/5.3/gcc_64/include/QtWidgets/qmessagebox.h \
		mainwindow2.h \
		dia_spd.h \
		../../qt/5.3/gcc_64/include/QtWidgets/QDialog \
		../../qt/5.3/gcc_64/include/QtWidgets/QVBoxLayout \
		../../qt/5.3/gcc_64/include/QtWidgets/qboxlayout.h \
		../../qt/5.3/gcc_64/include/QtWidgets/qlayout.h \
		../../qt/5.3/gcc_64/include/QtWidgets/qlayoutitem.h \
		../../qt/5.3/gcc_64/include/QtWidgets/qgridlayout.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

mainwindow2.o: mainwindow2.cpp mainwindow2.h \
		../../qt/5.3/gcc_64/include/QtWidgets/QMainWindow \
		../../qt/5.3/gcc_64/include/QtWidgets/qmainwindow.h \
		../../qt/5.3/gcc_64/include/QtWidgets/qwidget.h \
		../../qt/5.3/gcc_64/include/QtGui/qwindowdefs.h \
		../../qt/5.3/gcc_64/include/QtCore/qglobal.h \
		../../qt/5.3/gcc_64/include/QtCore/qconfig.h \
		../../qt/5.3/gcc_64/include/QtCore/qfeatures.h \
		../../qt/5.3/gcc_64/include/QtCore/qsystemdetection.h \
		../../qt/5.3/gcc_64/include/QtCore/qprocessordetection.h \
		../../qt/5.3/gcc_64/include/QtCore/qcompilerdetection.h \
		../../qt/5.3/gcc_64/include/QtCore/qtypeinfo.h \
		../../qt/5.3/gcc_64/include/QtCore/qtypetraits.h \
		../../qt/5.3/gcc_64/include/QtCore/qsysinfo.h \
		../../qt/5.3/gcc_64/include/QtCore/qlogging.h \
		../../qt/5.3/gcc_64/include/QtCore/qflags.h \
		../../qt/5.3/gcc_64/include/QtCore/qatomic.h \
		../../qt/5.3/gcc_64/include/QtCore/qbasicatomic.h \
		../../qt/5.3/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../qt/5.3/gcc_64/include/QtCore/qgenericatomic.h \
		../../qt/5.3/gcc_64/include/QtCore/qatomic_msvc.h \
		../../qt/5.3/gcc_64/include/QtCore/qatomic_armv7.h \
		../../qt/5.3/gcc_64/include/QtCore/qatomic_armv6.h \
		../../qt/5.3/gcc_64/include/QtCore/qatomic_armv5.h \
		../../qt/5.3/gcc_64/include/QtCore/qatomic_ia64.h \
		../../qt/5.3/gcc_64/include/QtCore/qatomic_mips.h \
		../../qt/5.3/gcc_64/include/QtCore/qatomic_x86.h \
		../../qt/5.3/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../qt/5.3/gcc_64/include/QtCore/qatomic_gcc.h \
		../../qt/5.3/gcc_64/include/QtCore/qatomic_unix.h \
		../../qt/5.3/gcc_64/include/QtCore/qglobalstatic.h \
		../../qt/5.3/gcc_64/include/QtCore/qmutex.h \
		../../qt/5.3/gcc_64/include/QtCore/qnumeric.h \
		../../qt/5.3/gcc_64/include/QtCore/qobjectdefs.h \
		../../qt/5.3/gcc_64/include/QtCore/qnamespace.h \
		../../qt/5.3/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../qt/5.3/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../qt/5.3/gcc_64/include/QtCore/qobject.h \
		../../qt/5.3/gcc_64/include/QtCore/qstring.h \
		../../qt/5.3/gcc_64/include/QtCore/qchar.h \
		../../qt/5.3/gcc_64/include/QtCore/qbytearray.h \
		../../qt/5.3/gcc_64/include/QtCore/qrefcount.h \
		../../qt/5.3/gcc_64/include/QtCore/qarraydata.h \
		../../qt/5.3/gcc_64/include/QtCore/qstringbuilder.h \
		../../qt/5.3/gcc_64/include/QtCore/qlist.h \
		../../qt/5.3/gcc_64/include/QtCore/qalgorithms.h \
		../../qt/5.3/gcc_64/include/QtCore/qiterator.h \
		../../qt/5.3/gcc_64/include/QtCore/qcoreevent.h \
		../../qt/5.3/gcc_64/include/QtCore/qscopedpointer.h \
		../../qt/5.3/gcc_64/include/QtCore/qmetatype.h \
		../../qt/5.3/gcc_64/include/QtCore/qvarlengtharray.h \
		../../qt/5.3/gcc_64/include/QtCore/qcontainerfwd.h \
		../../qt/5.3/gcc_64/include/QtCore/qisenum.h \
		../../qt/5.3/gcc_64/include/QtCore/qobject_impl.h \
		../../qt/5.3/gcc_64/include/QtCore/qmargins.h \
		../../qt/5.3/gcc_64/include/QtGui/qpaintdevice.h \
		../../qt/5.3/gcc_64/include/QtCore/qrect.h \
		../../qt/5.3/gcc_64/include/QtCore/qsize.h \
		../../qt/5.3/gcc_64/include/QtCore/qpoint.h \
		../../qt/5.3/gcc_64/include/QtGui/qpalette.h \
		../../qt/5.3/gcc_64/include/QtGui/qcolor.h \
		../../qt/5.3/gcc_64/include/QtGui/qrgb.h \
		../../qt/5.3/gcc_64/include/QtCore/qstringlist.h \
		../../qt/5.3/gcc_64/include/QtCore/qdatastream.h \
		../../qt/5.3/gcc_64/include/QtCore/qiodevice.h \
		../../qt/5.3/gcc_64/include/QtCore/qpair.h \
		../../qt/5.3/gcc_64/include/QtCore/qregexp.h \
		../../qt/5.3/gcc_64/include/QtCore/qstringmatcher.h \
		../../qt/5.3/gcc_64/include/QtGui/qbrush.h \
		../../qt/5.3/gcc_64/include/QtCore/qvector.h \
		../../qt/5.3/gcc_64/include/QtGui/qmatrix.h \
		../../qt/5.3/gcc_64/include/QtGui/qpolygon.h \
		../../qt/5.3/gcc_64/include/QtGui/qregion.h \
		../../qt/5.3/gcc_64/include/QtCore/qline.h \
		../../qt/5.3/gcc_64/include/QtGui/qtransform.h \
		../../qt/5.3/gcc_64/include/QtGui/qpainterpath.h \
		../../qt/5.3/gcc_64/include/QtGui/qimage.h \
		../../qt/5.3/gcc_64/include/QtGui/qpixmap.h \
		../../qt/5.3/gcc_64/include/QtCore/qsharedpointer.h \
		../../qt/5.3/gcc_64/include/QtCore/qshareddata.h \
		../../qt/5.3/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../qt/5.3/gcc_64/include/QtCore/qhash.h \
		../../qt/5.3/gcc_64/include/QtGui/qfont.h \
		../../qt/5.3/gcc_64/include/QtGui/qfontmetrics.h \
		../../qt/5.3/gcc_64/include/QtGui/qfontinfo.h \
		../../qt/5.3/gcc_64/include/QtWidgets/qsizepolicy.h \
		../../qt/5.3/gcc_64/include/QtGui/qcursor.h \
		../../qt/5.3/gcc_64/include/QtGui/qkeysequence.h \
		../../qt/5.3/gcc_64/include/QtGui/qevent.h \
		../../qt/5.3/gcc_64/include/QtCore/qvariant.h \
		../../qt/5.3/gcc_64/include/QtCore/qmap.h \
		../../qt/5.3/gcc_64/include/QtCore/qdebug.h \
		../../qt/5.3/gcc_64/include/QtCore/qtextstream.h \
		../../qt/5.3/gcc_64/include/QtCore/qlocale.h \
		../../qt/5.3/gcc_64/include/QtCore/qset.h \
		../../qt/5.3/gcc_64/include/QtCore/qcontiguouscache.h \
		../../qt/5.3/gcc_64/include/QtCore/qurl.h \
		../../qt/5.3/gcc_64/include/QtCore/qurlquery.h \
		../../qt/5.3/gcc_64/include/QtCore/qfile.h \
		../../qt/5.3/gcc_64/include/QtCore/qfiledevice.h \
		../../qt/5.3/gcc_64/include/QtGui/qvector2d.h \
		../../qt/5.3/gcc_64/include/QtGui/qtouchdevice.h \
		../../qt/5.3/gcc_64/include/QtWidgets/qtabwidget.h \
		../../qt/5.3/gcc_64/include/QtGui/qicon.h \
		../../qt/5.3/gcc_64/include/QtWidgets/QApplication \
		../../qt/5.3/gcc_64/include/QtWidgets/qapplication.h \
		../../qt/5.3/gcc_64/include/QtCore/qcoreapplication.h \
		../../qt/5.3/gcc_64/include/QtCore/qeventloop.h \
		../../qt/5.3/gcc_64/include/QtWidgets/qdesktopwidget.h \
		../../qt/5.3/gcc_64/include/QtGui/qguiapplication.h \
		../../qt/5.3/gcc_64/include/QtGui/qinputmethod.h \
		../../qt/5.3/gcc_64/include/QtWidgets/QAction \
		../../qt/5.3/gcc_64/include/QtWidgets/qaction.h \
		../../qt/5.3/gcc_64/include/QtWidgets/qactiongroup.h \
		../../qt/5.3/gcc_64/include/QtWidgets/QMenu \
		../../qt/5.3/gcc_64/include/QtWidgets/qmenu.h \
		../../qt/5.3/gcc_64/include/QtWidgets/QFileDialog \
		../../qt/5.3/gcc_64/include/QtWidgets/qfiledialog.h \
		../../qt/5.3/gcc_64/include/QtCore/qdir.h \
		../../qt/5.3/gcc_64/include/QtCore/qfileinfo.h \
		../../qt/5.3/gcc_64/include/QtWidgets/qdialog.h \
		../../qt/5.3/gcc_64/include/QtCore/QFile \
		../../qt/5.3/gcc_64/include/QtCore/QTextStream \
		../../qt/5.3/gcc_64/include/QtWidgets/QToolBar \
		../../qt/5.3/gcc_64/include/QtWidgets/qtoolbar.h \
		../../qt/5.3/gcc_64/include/QtWidgets/QTextEdit \
		../../qt/5.3/gcc_64/include/QtWidgets/qtextedit.h \
		../../qt/5.3/gcc_64/include/QtWidgets/qabstractscrollarea.h \
		../../qt/5.3/gcc_64/include/QtWidgets/qframe.h \
		../../qt/5.3/gcc_64/include/QtGui/qtextdocument.h \
		../../qt/5.3/gcc_64/include/QtGui/qtextoption.h \
		../../qt/5.3/gcc_64/include/QtGui/qtextcursor.h \
		../../qt/5.3/gcc_64/include/QtGui/qtextformat.h \
		../../qt/5.3/gcc_64/include/QtGui/qpen.h \
		../../qt/5.3/gcc_64/include/QtCore/QString \
		../../qt/5.3/gcc_64/include/QtWidgets/QMenuBar \
		../../qt/5.3/gcc_64/include/QtWidgets/qmenubar.h \
		../../qt/5.3/gcc_64/include/QtGui/QMouseEvent \
		../../qt/5.3/gcc_64/include/QtWidgets/QPushButton \
		../../qt/5.3/gcc_64/include/QtWidgets/qpushbutton.h \
		../../qt/5.3/gcc_64/include/QtWidgets/qabstractbutton.h \
		dia_spd.h \
		../../qt/5.3/gcc_64/include/QtWidgets/QDialog \
		../../qt/5.3/gcc_64/include/QtWidgets/QVBoxLayout \
		../../qt/5.3/gcc_64/include/QtWidgets/qboxlayout.h \
		../../qt/5.3/gcc_64/include/QtWidgets/qlayout.h \
		../../qt/5.3/gcc_64/include/QtWidgets/qlayoutitem.h \
		../../qt/5.3/gcc_64/include/QtWidgets/qgridlayout.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow2.o mainwindow2.cpp

test.o: test.cpp ../../qt/5.3/gcc_64/include/QtWidgets/QApplication \
		../../qt/5.3/gcc_64/include/QtWidgets/qapplication.h \
		../../qt/5.3/gcc_64/include/QtCore/qcoreapplication.h \
		../../qt/5.3/gcc_64/include/QtCore/qglobal.h \
		../../qt/5.3/gcc_64/include/QtCore/qconfig.h \
		../../qt/5.3/gcc_64/include/QtCore/qfeatures.h \
		../../qt/5.3/gcc_64/include/QtCore/qsystemdetection.h \
		../../qt/5.3/gcc_64/include/QtCore/qprocessordetection.h \
		../../qt/5.3/gcc_64/include/QtCore/qcompilerdetection.h \
		../../qt/5.3/gcc_64/include/QtCore/qtypeinfo.h \
		../../qt/5.3/gcc_64/include/QtCore/qtypetraits.h \
		../../qt/5.3/gcc_64/include/QtCore/qsysinfo.h \
		../../qt/5.3/gcc_64/include/QtCore/qlogging.h \
		../../qt/5.3/gcc_64/include/QtCore/qflags.h \
		../../qt/5.3/gcc_64/include/QtCore/qatomic.h \
		../../qt/5.3/gcc_64/include/QtCore/qbasicatomic.h \
		../../qt/5.3/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../qt/5.3/gcc_64/include/QtCore/qgenericatomic.h \
		../../qt/5.3/gcc_64/include/QtCore/qatomic_msvc.h \
		../../qt/5.3/gcc_64/include/QtCore/qatomic_armv7.h \
		../../qt/5.3/gcc_64/include/QtCore/qatomic_armv6.h \
		../../qt/5.3/gcc_64/include/QtCore/qatomic_armv5.h \
		../../qt/5.3/gcc_64/include/QtCore/qatomic_ia64.h \
		../../qt/5.3/gcc_64/include/QtCore/qatomic_mips.h \
		../../qt/5.3/gcc_64/include/QtCore/qatomic_x86.h \
		../../qt/5.3/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../qt/5.3/gcc_64/include/QtCore/qatomic_gcc.h \
		../../qt/5.3/gcc_64/include/QtCore/qatomic_unix.h \
		../../qt/5.3/gcc_64/include/QtCore/qglobalstatic.h \
		../../qt/5.3/gcc_64/include/QtCore/qmutex.h \
		../../qt/5.3/gcc_64/include/QtCore/qnumeric.h \
		../../qt/5.3/gcc_64/include/QtCore/qstring.h \
		../../qt/5.3/gcc_64/include/QtCore/qchar.h \
		../../qt/5.3/gcc_64/include/QtCore/qbytearray.h \
		../../qt/5.3/gcc_64/include/QtCore/qrefcount.h \
		../../qt/5.3/gcc_64/include/QtCore/qnamespace.h \
		../../qt/5.3/gcc_64/include/QtCore/qarraydata.h \
		../../qt/5.3/gcc_64/include/QtCore/qstringbuilder.h \
		../../qt/5.3/gcc_64/include/QtCore/qobject.h \
		../../qt/5.3/gcc_64/include/QtCore/qobjectdefs.h \
		../../qt/5.3/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../qt/5.3/gcc_64/include/QtCore/qlist.h \
		../../qt/5.3/gcc_64/include/QtCore/qalgorithms.h \
		../../qt/5.3/gcc_64/include/QtCore/qiterator.h \
		../../qt/5.3/gcc_64/include/QtCore/qcoreevent.h \
		../../qt/5.3/gcc_64/include/QtCore/qscopedpointer.h \
		../../qt/5.3/gcc_64/include/QtCore/qmetatype.h \
		../../qt/5.3/gcc_64/include/QtCore/qvarlengtharray.h \
		../../qt/5.3/gcc_64/include/QtCore/qcontainerfwd.h \
		../../qt/5.3/gcc_64/include/QtCore/qisenum.h \
		../../qt/5.3/gcc_64/include/QtCore/qobject_impl.h \
		../../qt/5.3/gcc_64/include/QtCore/qeventloop.h \
		../../qt/5.3/gcc_64/include/QtGui/qwindowdefs.h \
		../../qt/5.3/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../qt/5.3/gcc_64/include/QtCore/qpoint.h \
		../../qt/5.3/gcc_64/include/QtCore/qsize.h \
		../../qt/5.3/gcc_64/include/QtGui/qcursor.h \
		../../qt/5.3/gcc_64/include/QtWidgets/qdesktopwidget.h \
		../../qt/5.3/gcc_64/include/QtWidgets/qwidget.h \
		../../qt/5.3/gcc_64/include/QtCore/qmargins.h \
		../../qt/5.3/gcc_64/include/QtGui/qpaintdevice.h \
		../../qt/5.3/gcc_64/include/QtCore/qrect.h \
		../../qt/5.3/gcc_64/include/QtGui/qpalette.h \
		../../qt/5.3/gcc_64/include/QtGui/qcolor.h \
		../../qt/5.3/gcc_64/include/QtGui/qrgb.h \
		../../qt/5.3/gcc_64/include/QtCore/qstringlist.h \
		../../qt/5.3/gcc_64/include/QtCore/qdatastream.h \
		../../qt/5.3/gcc_64/include/QtCore/qiodevice.h \
		../../qt/5.3/gcc_64/include/QtCore/qpair.h \
		../../qt/5.3/gcc_64/include/QtCore/qregexp.h \
		../../qt/5.3/gcc_64/include/QtCore/qstringmatcher.h \
		../../qt/5.3/gcc_64/include/QtGui/qbrush.h \
		../../qt/5.3/gcc_64/include/QtCore/qvector.h \
		../../qt/5.3/gcc_64/include/QtGui/qmatrix.h \
		../../qt/5.3/gcc_64/include/QtGui/qpolygon.h \
		../../qt/5.3/gcc_64/include/QtGui/qregion.h \
		../../qt/5.3/gcc_64/include/QtCore/qline.h \
		../../qt/5.3/gcc_64/include/QtGui/qtransform.h \
		../../qt/5.3/gcc_64/include/QtGui/qpainterpath.h \
		../../qt/5.3/gcc_64/include/QtGui/qimage.h \
		../../qt/5.3/gcc_64/include/QtGui/qpixmap.h \
		../../qt/5.3/gcc_64/include/QtCore/qsharedpointer.h \
		../../qt/5.3/gcc_64/include/QtCore/qshareddata.h \
		../../qt/5.3/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../qt/5.3/gcc_64/include/QtCore/qhash.h \
		../../qt/5.3/gcc_64/include/QtGui/qfont.h \
		../../qt/5.3/gcc_64/include/QtGui/qfontmetrics.h \
		../../qt/5.3/gcc_64/include/QtGui/qfontinfo.h \
		../../qt/5.3/gcc_64/include/QtWidgets/qsizepolicy.h \
		../../qt/5.3/gcc_64/include/QtGui/qkeysequence.h \
		../../qt/5.3/gcc_64/include/QtGui/qevent.h \
		../../qt/5.3/gcc_64/include/QtCore/qvariant.h \
		../../qt/5.3/gcc_64/include/QtCore/qmap.h \
		../../qt/5.3/gcc_64/include/QtCore/qdebug.h \
		../../qt/5.3/gcc_64/include/QtCore/qtextstream.h \
		../../qt/5.3/gcc_64/include/QtCore/qlocale.h \
		../../qt/5.3/gcc_64/include/QtCore/qset.h \
		../../qt/5.3/gcc_64/include/QtCore/qcontiguouscache.h \
		../../qt/5.3/gcc_64/include/QtCore/qurl.h \
		../../qt/5.3/gcc_64/include/QtCore/qurlquery.h \
		../../qt/5.3/gcc_64/include/QtCore/qfile.h \
		../../qt/5.3/gcc_64/include/QtCore/qfiledevice.h \
		../../qt/5.3/gcc_64/include/QtGui/qvector2d.h \
		../../qt/5.3/gcc_64/include/QtGui/qtouchdevice.h \
		../../qt/5.3/gcc_64/include/QtGui/qguiapplication.h \
		../../qt/5.3/gcc_64/include/QtGui/qinputmethod.h \
		mainwindow.h \
		../../qt/5.3/gcc_64/include/QtWidgets/QMainWindow \
		../../qt/5.3/gcc_64/include/QtWidgets/qmainwindow.h \
		../../qt/5.3/gcc_64/include/QtWidgets/qtabwidget.h \
		../../qt/5.3/gcc_64/include/QtGui/qicon.h \
		../../qt/5.3/gcc_64/include/QtWidgets/QAction \
		../../qt/5.3/gcc_64/include/QtWidgets/qaction.h \
		../../qt/5.3/gcc_64/include/QtWidgets/qactiongroup.h \
		../../qt/5.3/gcc_64/include/QtWidgets/QMenu \
		../../qt/5.3/gcc_64/include/QtWidgets/qmenu.h \
		../../qt/5.3/gcc_64/include/QtWidgets/QFileDialog \
		../../qt/5.3/gcc_64/include/QtWidgets/qfiledialog.h \
		../../qt/5.3/gcc_64/include/QtCore/qdir.h \
		../../qt/5.3/gcc_64/include/QtCore/qfileinfo.h \
		../../qt/5.3/gcc_64/include/QtWidgets/qdialog.h \
		../../qt/5.3/gcc_64/include/QtCore/QFile \
		../../qt/5.3/gcc_64/include/QtCore/QTextStream \
		../../qt/5.3/gcc_64/include/QtWidgets/QToolBar \
		../../qt/5.3/gcc_64/include/QtWidgets/qtoolbar.h \
		../../qt/5.3/gcc_64/include/QtWidgets/QTextEdit \
		../../qt/5.3/gcc_64/include/QtWidgets/qtextedit.h \
		../../qt/5.3/gcc_64/include/QtWidgets/qabstractscrollarea.h \
		../../qt/5.3/gcc_64/include/QtWidgets/qframe.h \
		../../qt/5.3/gcc_64/include/QtGui/qtextdocument.h \
		../../qt/5.3/gcc_64/include/QtGui/qtextoption.h \
		../../qt/5.3/gcc_64/include/QtGui/qtextcursor.h \
		../../qt/5.3/gcc_64/include/QtGui/qtextformat.h \
		../../qt/5.3/gcc_64/include/QtGui/qpen.h \
		../../qt/5.3/gcc_64/include/QtCore/QString \
		../../qt/5.3/gcc_64/include/QtWidgets/QMenuBar \
		../../qt/5.3/gcc_64/include/QtWidgets/qmenubar.h \
		../../qt/5.3/gcc_64/include/QtGui/QMouseEvent \
		../../qt/5.3/gcc_64/include/QtWidgets/QPushButton \
		../../qt/5.3/gcc_64/include/QtWidgets/qpushbutton.h \
		../../qt/5.3/gcc_64/include/QtWidgets/qabstractbutton.h \
		../../qt/5.3/gcc_64/include/QtWidgets/QLabel \
		../../qt/5.3/gcc_64/include/QtWidgets/qlabel.h \
		../../qt/5.3/gcc_64/include/QtWidgets/QLineEdit \
		../../qt/5.3/gcc_64/include/QtWidgets/qlineedit.h \
		../../qt/5.3/gcc_64/include/QtWidgets/QMessageBox \
		../../qt/5.3/gcc_64/include/QtWidgets/qmessagebox.h \
		mainwindow2.h \
		dia_spd.h \
		../../qt/5.3/gcc_64/include/QtWidgets/QDialog \
		../../qt/5.3/gcc_64/include/QtWidgets/QVBoxLayout \
		../../qt/5.3/gcc_64/include/QtWidgets/qboxlayout.h \
		../../qt/5.3/gcc_64/include/QtWidgets/qlayout.h \
		../../qt/5.3/gcc_64/include/QtWidgets/qlayoutitem.h \
		../../qt/5.3/gcc_64/include/QtWidgets/qgridlayout.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o test.o test.cpp

dia_spd.o: dia_spd.cpp dia_spd.h \
		../../qt/5.3/gcc_64/include/QtWidgets/QDialog \
		../../qt/5.3/gcc_64/include/QtWidgets/qdialog.h \
		../../qt/5.3/gcc_64/include/QtWidgets/qwidget.h \
		../../qt/5.3/gcc_64/include/QtGui/qwindowdefs.h \
		../../qt/5.3/gcc_64/include/QtCore/qglobal.h \
		../../qt/5.3/gcc_64/include/QtCore/qconfig.h \
		../../qt/5.3/gcc_64/include/QtCore/qfeatures.h \
		../../qt/5.3/gcc_64/include/QtCore/qsystemdetection.h \
		../../qt/5.3/gcc_64/include/QtCore/qprocessordetection.h \
		../../qt/5.3/gcc_64/include/QtCore/qcompilerdetection.h \
		../../qt/5.3/gcc_64/include/QtCore/qtypeinfo.h \
		../../qt/5.3/gcc_64/include/QtCore/qtypetraits.h \
		../../qt/5.3/gcc_64/include/QtCore/qsysinfo.h \
		../../qt/5.3/gcc_64/include/QtCore/qlogging.h \
		../../qt/5.3/gcc_64/include/QtCore/qflags.h \
		../../qt/5.3/gcc_64/include/QtCore/qatomic.h \
		../../qt/5.3/gcc_64/include/QtCore/qbasicatomic.h \
		../../qt/5.3/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../qt/5.3/gcc_64/include/QtCore/qgenericatomic.h \
		../../qt/5.3/gcc_64/include/QtCore/qatomic_msvc.h \
		../../qt/5.3/gcc_64/include/QtCore/qatomic_armv7.h \
		../../qt/5.3/gcc_64/include/QtCore/qatomic_armv6.h \
		../../qt/5.3/gcc_64/include/QtCore/qatomic_armv5.h \
		../../qt/5.3/gcc_64/include/QtCore/qatomic_ia64.h \
		../../qt/5.3/gcc_64/include/QtCore/qatomic_mips.h \
		../../qt/5.3/gcc_64/include/QtCore/qatomic_x86.h \
		../../qt/5.3/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../qt/5.3/gcc_64/include/QtCore/qatomic_gcc.h \
		../../qt/5.3/gcc_64/include/QtCore/qatomic_unix.h \
		../../qt/5.3/gcc_64/include/QtCore/qglobalstatic.h \
		../../qt/5.3/gcc_64/include/QtCore/qmutex.h \
		../../qt/5.3/gcc_64/include/QtCore/qnumeric.h \
		../../qt/5.3/gcc_64/include/QtCore/qobjectdefs.h \
		../../qt/5.3/gcc_64/include/QtCore/qnamespace.h \
		../../qt/5.3/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../qt/5.3/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../qt/5.3/gcc_64/include/QtCore/qobject.h \
		../../qt/5.3/gcc_64/include/QtCore/qstring.h \
		../../qt/5.3/gcc_64/include/QtCore/qchar.h \
		../../qt/5.3/gcc_64/include/QtCore/qbytearray.h \
		../../qt/5.3/gcc_64/include/QtCore/qrefcount.h \
		../../qt/5.3/gcc_64/include/QtCore/qarraydata.h \
		../../qt/5.3/gcc_64/include/QtCore/qstringbuilder.h \
		../../qt/5.3/gcc_64/include/QtCore/qlist.h \
		../../qt/5.3/gcc_64/include/QtCore/qalgorithms.h \
		../../qt/5.3/gcc_64/include/QtCore/qiterator.h \
		../../qt/5.3/gcc_64/include/QtCore/qcoreevent.h \
		../../qt/5.3/gcc_64/include/QtCore/qscopedpointer.h \
		../../qt/5.3/gcc_64/include/QtCore/qmetatype.h \
		../../qt/5.3/gcc_64/include/QtCore/qvarlengtharray.h \
		../../qt/5.3/gcc_64/include/QtCore/qcontainerfwd.h \
		../../qt/5.3/gcc_64/include/QtCore/qisenum.h \
		../../qt/5.3/gcc_64/include/QtCore/qobject_impl.h \
		../../qt/5.3/gcc_64/include/QtCore/qmargins.h \
		../../qt/5.3/gcc_64/include/QtGui/qpaintdevice.h \
		../../qt/5.3/gcc_64/include/QtCore/qrect.h \
		../../qt/5.3/gcc_64/include/QtCore/qsize.h \
		../../qt/5.3/gcc_64/include/QtCore/qpoint.h \
		../../qt/5.3/gcc_64/include/QtGui/qpalette.h \
		../../qt/5.3/gcc_64/include/QtGui/qcolor.h \
		../../qt/5.3/gcc_64/include/QtGui/qrgb.h \
		../../qt/5.3/gcc_64/include/QtCore/qstringlist.h \
		../../qt/5.3/gcc_64/include/QtCore/qdatastream.h \
		../../qt/5.3/gcc_64/include/QtCore/qiodevice.h \
		../../qt/5.3/gcc_64/include/QtCore/qpair.h \
		../../qt/5.3/gcc_64/include/QtCore/qregexp.h \
		../../qt/5.3/gcc_64/include/QtCore/qstringmatcher.h \
		../../qt/5.3/gcc_64/include/QtGui/qbrush.h \
		../../qt/5.3/gcc_64/include/QtCore/qvector.h \
		../../qt/5.3/gcc_64/include/QtGui/qmatrix.h \
		../../qt/5.3/gcc_64/include/QtGui/qpolygon.h \
		../../qt/5.3/gcc_64/include/QtGui/qregion.h \
		../../qt/5.3/gcc_64/include/QtCore/qline.h \
		../../qt/5.3/gcc_64/include/QtGui/qtransform.h \
		../../qt/5.3/gcc_64/include/QtGui/qpainterpath.h \
		../../qt/5.3/gcc_64/include/QtGui/qimage.h \
		../../qt/5.3/gcc_64/include/QtGui/qpixmap.h \
		../../qt/5.3/gcc_64/include/QtCore/qsharedpointer.h \
		../../qt/5.3/gcc_64/include/QtCore/qshareddata.h \
		../../qt/5.3/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../qt/5.3/gcc_64/include/QtCore/qhash.h \
		../../qt/5.3/gcc_64/include/QtGui/qfont.h \
		../../qt/5.3/gcc_64/include/QtGui/qfontmetrics.h \
		../../qt/5.3/gcc_64/include/QtGui/qfontinfo.h \
		../../qt/5.3/gcc_64/include/QtWidgets/qsizepolicy.h \
		../../qt/5.3/gcc_64/include/QtGui/qcursor.h \
		../../qt/5.3/gcc_64/include/QtGui/qkeysequence.h \
		../../qt/5.3/gcc_64/include/QtGui/qevent.h \
		../../qt/5.3/gcc_64/include/QtCore/qvariant.h \
		../../qt/5.3/gcc_64/include/QtCore/qmap.h \
		../../qt/5.3/gcc_64/include/QtCore/qdebug.h \
		../../qt/5.3/gcc_64/include/QtCore/qtextstream.h \
		../../qt/5.3/gcc_64/include/QtCore/qlocale.h \
		../../qt/5.3/gcc_64/include/QtCore/qset.h \
		../../qt/5.3/gcc_64/include/QtCore/qcontiguouscache.h \
		../../qt/5.3/gcc_64/include/QtCore/qurl.h \
		../../qt/5.3/gcc_64/include/QtCore/qurlquery.h \
		../../qt/5.3/gcc_64/include/QtCore/qfile.h \
		../../qt/5.3/gcc_64/include/QtCore/qfiledevice.h \
		../../qt/5.3/gcc_64/include/QtGui/qvector2d.h \
		../../qt/5.3/gcc_64/include/QtGui/qtouchdevice.h \
		../../qt/5.3/gcc_64/include/QtWidgets/QPushButton \
		../../qt/5.3/gcc_64/include/QtWidgets/qpushbutton.h \
		../../qt/5.3/gcc_64/include/QtWidgets/qabstractbutton.h \
		../../qt/5.3/gcc_64/include/QtGui/qicon.h \
		../../qt/5.3/gcc_64/include/QtWidgets/QVBoxLayout \
		../../qt/5.3/gcc_64/include/QtWidgets/qboxlayout.h \
		../../qt/5.3/gcc_64/include/QtWidgets/qlayout.h \
		../../qt/5.3/gcc_64/include/QtWidgets/qlayoutitem.h \
		../../qt/5.3/gcc_64/include/QtWidgets/qgridlayout.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dia_spd.o dia_spd.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_mainwindow2.o: moc_mainwindow2.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow2.o moc_mainwindow2.cpp

moc_dia_spd.o: moc_dia_spd.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dia_spd.o moc_dia_spd.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

