######################################################################
# Automatically generated by qmake (3.0) ?? 9? 26 15:22:43 2014
######################################################################

TEMPLATE = app
TARGET = test
INCLUDEPATH += .
QT += qml quick widgets core
# Input
HEADERS += mainwindow.h mainwindow2.h dia_spd.h 
SOURCES += mainwindow.cpp mainwindow2.cpp test.cpp dia_spd.cpp
